import type { CorridorStation, DisruptionTemplate, Train } from './types';

/** Session start: Tuesday 16:32, peak evening traffic on the corridor. */
export const SESSION_START_MINUTES = 16 * 60 + 32;

export const CORRIDOR_STATIONS: CorridorStation[] = [
  { id: 'ahar', name: 'Hamburg Hbf', short: 'HH', offset: 0 },
  { id: 'ahgb', name: 'Hamburg-Harburg', short: 'HBG', offset: 0.09 },
  { id: 'alun', name: 'Lüneburg', short: 'LBG', offset: 0.26 },
  { id: 'auel', name: 'Uelzen', short: 'UE', offset: 0.47 },
  { id: 'acel', name: 'Celle', short: 'CE', offset: 0.76 },
  { id: 'ahan', name: 'Hannover Hbf', short: 'H', offset: 1 },
];

/** Platforms free for re-routing at Hannover Hbf during the session. */
export const SPARE_PLATFORMS = [9, 11, 13];

const H = (hours: number, minutes: number) => hours * 60 + minutes;

export const INITIAL_TRAINS: Train[] = [
  {
    id: 'ice574',
    service: 'ICE 574',
    category: 'ICE',
    origin: 'Hamburg-Altona',
    destination: 'Stuttgart Hbf',
    platform: 6,
    scheduledDeparture: H(16, 7),
    scheduledArrival: H(17, 24),
    fromOffset: 0,
    toOffset: 1,
    passengersOnboard: 412,
    passengersBoarding: 95,
    delayMin: 0,
    status: 'on-time',
    connections: [
      {
        id: 'ice574-ice692',
        service: 'ICE 692',
        category: 'ICE',
        destination: 'Frankfurt (Main) Hbf',
        platform: 12,
        scheduledDeparture: H(17, 33),
        transferBufferMin: 9,
        transferPassengers: 84,
        maxHoldMin: 11,
        onwardPassengers: 356,
      },
      {
        id: 'ice574-re60',
        service: 'RE 60',
        category: 'RE',
        destination: 'Braunschweig Hbf',
        platform: 8,
        scheduledDeparture: H(17, 35),
        transferBufferMin: 11,
        transferPassengers: 46,
        maxHoldMin: 6,
        onwardPassengers: 188,
      },
    ],
  },
  {
    id: 'ice787',
    service: 'ICE 787',
    category: 'ICE',
    origin: 'Hamburg Hbf',
    destination: 'München Hbf',
    platform: 8,
    scheduledDeparture: H(16, 23),
    scheduledArrival: H(17, 41),
    fromOffset: 0,
    toOffset: 1,
    passengersOnboard: 386,
    passengersBoarding: 118,
    delayMin: 0,
    status: 'on-time',
    connections: [
      {
        id: 'ice787-ice1035',
        service: 'ICE 1035',
        category: 'ICE',
        destination: 'Berlin Hbf',
        platform: 9,
        scheduledDeparture: H(17, 51),
        transferBufferMin: 10,
        transferPassengers: 71,
        maxHoldMin: 8,
        onwardPassengers: 402,
      },
    ],
  },
  {
    id: 'ic2073',
    service: 'IC 2073',
    category: 'IC',
    origin: 'Hamburg-Altona',
    destination: 'Karlsruhe Hbf',
    platform: 7,
    scheduledDeparture: H(15, 58),
    scheduledArrival: H(17, 22),
    fromOffset: 0,
    toOffset: 1,
    passengersOnboard: 244,
    passengersBoarding: 61,
    delayMin: 0,
    status: 'on-time',
    connections: [
      {
        id: 'ic2073-s5',
        service: 'S 5',
        category: 'RB',
        destination: 'Hannover Flughafen',
        platform: 2,
        scheduledDeparture: H(17, 30),
        transferBufferMin: 8,
        transferPassengers: 38,
        maxHoldMin: 5,
        onwardPassengers: 96,
      },
    ],
  },
  {
    id: 're30',
    service: 'RE 30',
    category: 'RE',
    origin: 'Hamburg Hbf',
    destination: 'Hannover Hbf',
    platform: 5,
    scheduledDeparture: H(15, 26),
    scheduledArrival: H(17, 16),
    fromOffset: 0,
    toOffset: 1,
    passengersOnboard: 318,
    passengersBoarding: 142,
    delayMin: 0,
    status: 'on-time',
    connections: [
      {
        id: 're30-ice596',
        service: 'ICE 596',
        category: 'ICE',
        destination: 'Göttingen',
        platform: 7,
        scheduledDeparture: H(17, 26),
        transferBufferMin: 10,
        transferPassengers: 62,
        maxHoldMin: 7,
        onwardPassengers: 298,
      },
    ],
  },
  {
    id: 'rb41',
    service: 'RB 41',
    category: 'RB',
    origin: 'Uelzen',
    destination: 'Hannover Hbf',
    platform: 3,
    scheduledDeparture: H(16, 21),
    scheduledArrival: H(17, 28),
    fromOffset: 0.47,
    toOffset: 1,
    passengersOnboard: 96,
    passengersBoarding: 44,
    delayMin: 0,
    status: 'on-time',
    connections: [
      {
        id: 'rb41-s3',
        service: 'S 3',
        category: 'RB',
        destination: 'Hildesheim Hbf',
        platform: 1,
        scheduledDeparture: H(17, 37),
        transferBufferMin: 9,
        transferPassengers: 24,
        maxHoldMin: 6,
        onwardPassengers: 74,
      },
    ],
  },
  {
    id: 'rb38',
    service: 'RB 38',
    category: 'RB',
    origin: 'Celle',
    destination: 'Hannover Hbf',
    platform: 4,
    scheduledDeparture: H(16, 47),
    scheduledArrival: H(17, 19),
    fromOffset: 0.76,
    toOffset: 1,
    passengersOnboard: 74,
    passengersBoarding: 31,
    delayMin: 0,
    status: 'on-time',
    connections: [],
  },
];

export const DISRUPTION_TEMPLATES: DisruptionTemplate[] = [
  {
    id: 'signal-uelzen',
    label: 'Signal failure',
    station: 'Uelzen',
    detail: 'Entry signal stuck at danger, single-track working through the station.',
    minDelayMin: 8,
    maxDelayMin: 19,
  },
  {
    id: 'points-celle',
    label: 'Points failure',
    station: 'north of Celle',
    detail: 'Point 42 will not lock, trains routed over the slow line.',
    minDelayMin: 6,
    maxDelayMin: 15,
  },
  {
    id: 'overhead-lueneburg',
    label: 'Overhead line fault',
    station: 'Lüneburg',
    detail: 'Reduced line speed under the damaged catenary section.',
    minDelayMin: 7,
    maxDelayMin: 17,
  },
  {
    id: 'door-harburg',
    label: 'Door fault',
    station: 'Hamburg-Harburg',
    detail: 'Coach 24 door will not release, extended dwell while staff isolate it.',
    minDelayMin: 3,
    maxDelayMin: 7,
  },
  {
    id: 'medical-onboard',
    label: 'Medical emergency on board',
    station: 'Bad Bevensen',
    detail: 'Unscheduled stop, paramedics attending a passenger.',
    minDelayMin: 5,
    maxDelayMin: 14,
  },
  {
    id: 'crossing-bevensen',
    label: 'Level crossing incident',
    station: 'near Bad Bevensen',
    detail: 'Barrier struck by road vehicle, line blocked while it is checked.',
    minDelayMin: 9,
    maxDelayMin: 21,
  },
  {
    id: 'freight-ahead',
    label: 'Freight service occupying the line',
    station: 'Uelzen',
    detail: 'Late-running freight ahead, no overtaking path until Celle.',
    minDelayMin: 4,
    maxDelayMin: 11,
  },
  {
    id: 'crew-celle',
    label: 'Late crew change',
    station: 'Celle',
    detail: 'Relief driver held up on an inbound service.',
    minDelayMin: 3,
    maxDelayMin: 8,
  },
];
